import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  background: {
    backgroundColor: 'white',
  },
  Container: {
    width: '100%',
    height: 100,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputForm: {
    width: '100%',
    height: 'auto',
    display: 'flex',
    justifyContent: 'center',
    marginTop: 20,
  },
  title: {
    fontSize: 30,
    fontWeight: '800',
    position: 'absolute',
  },
  backButton: {
    width: 27,
    height: 27,
    marginRight: 320,
    marginTop: 5,
  },
  inputTitle: {
    fontSize: 25,
    marginLeft: 30,
    fontWeight: 800,
  },
  textArea: {
    height: 80,
    margin: 30,
    marginTop: 15,
    textAlignVertical: 'top',
    padding: 15,
    backgroundColor: '#F7F7F7',
    borderRadius: 5,
  },
  textArea2: {
    height: 300,
    margin: 30,
    marginTop: 15,
    textAlignVertical: 'top',
    padding: 15,
    backgroundColor: '#F7F7F7',
    borderRadius: 5,
  },
  imageListContainer: {
    paddingHorizontal: 20,
    marginTop: 10,
    paddingBottom: 20,
  },
  imageItemContainer: {
    marginRight: 15,
    position: 'relative',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 5,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  selectedImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
  },
  removeImageButton: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 28,
    height: 28,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeImageText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    lineHeight: 24,
  },
  imageUploadButton: {
    width: 150,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F7F7F7',
    marginHorizontal: 30,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignSelf: 'flex-end',
    marginBottom: 20,
  },
  imageIcon: {
    width: 22,
    height: 22,
    marginRight: 8,
    tintColor: '#333',
  },
  imageUploadText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
  },
  submitButton: {
    backgroundColor: '#7DCA79',
    marginHorizontal: 30,
    marginVertical: 30,
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
  },
});

export default styles;